spring.application.name=backend

# SQL Server connection
spring.datasource.url=${DB_URL:jdbc:sqlserver://localhost:5144;databaseName=bizflow;encrypt=false;trustServerCertificate=true}
spring.datasource.username=${DB_USERNAME:sa}
spring.datasource.password=${DB_PASSWORD}

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=${JPA_DDL_AUTO:update}
spring.jpa.show-sql=${JPA_SHOW_SQL:true}
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect

scalar.enabled=true
scalar.url=https://example.com/openapi.json